### ISSUE TITLE
Special characters break the addon

### ISSUE THREAD

**Issue by fthiesse** [b-jesch/service.fritzbox.callmonitor#1]
Hey,

incomming calls from persons that have special characters (like "ß") in their name break the addon.

18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] 'ascii' codec can't encode character u'\xdf' in position 4: ordinal not in range(128)
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] In module:
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] At line:   373
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] In file:   /home/fthiesse/.kodi/addons/service.fritzbox.callmonitor/default.py
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] 'ascii' codec can't encode character u'\xdf' in position 4: ordinal not in range(128)
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] In module:
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] At line:   238
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] In file:   /home/fthiesse/.kodi/addons/service.fritzbox.callmonitor/default.py
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] 'ascii' codec can't encode character u'\xdf' in position 4: ordinal not in range(128)
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] In module:
18:03:27 T:2783959872   ERROR: [service.fritzbox.callmonitor] At line:   202

**Comment by b-jesch** [comment]
Fixed!
