### ISSUE TITLE
Weird issue: callmonitor works on one machine, don't work on another

### ISSUE THREAD

**Issue by b-jesch** [b-jesch/service.fritzbox.callmonitor#5]
Have a crazy issue on one of my two machines in my home network. Both machines are identical (x86 based, kodibuntu updated to Jarvis, Kernel 3.13, Python 2.7.6), both connected to fritzbox. Also same plugin version of course.

One machine  doesn't seem to initiate the pytzbox module, there's no login attempt at startup (fritzbox log). Directories and files are absolute identical on both machines. The only difference I see is a missing pytzbox.pyo in /resources/lib/phonebooks.

Sorry but I have no clue. Maybe a issue with PhoneBookFacade?

Reverting to 1.4.5 and it works again.

[kodi.log.txt](https://github.com/b-jesch/service.fritzbox.callmonitor/files/412818/kodi.log.txt)

**Comment by lutzleonhardt** [comment]
Hi @b-jesch,

I will have a look at thie issue this week.

**Comment by lutzleonhardt** [comment]
Hi @b-jesch,

you're right, it was an issue in PhoneBookFacade. I've fixed it right now. Could you please verify it?
Thx

**Comment by b-jesch** [comment]
Verified. It runs now ok on my two machines.

> 17:21:11 T:139855854028544  NOTICE: [service.fritzbox.callmonitor] Looking for all phonebook modules in /home/kodi/.kodi/addons/setzbox.callmonitor/resources/lib/PhoneBooks
> 17:21:11 T:139855854028544  NOTICE: [service.fritzbox.callmonitor] Found module AppleCloud.py - try to dynamic import resources.lioks.AppleCloud
> 17:21:12 T:139855854028544  NOTICE: [service.fritzbox.callmonitor] Use phonebook class AppleCloud
> 17:21:12 T:139855854028544  NOTICE: [service.fritzbox.callmonitor] Found module PytzBox.py - try to dynamic import resources.lib.P.PytzBox
> 17:21:12 T:139855854028544  NOTICE: [service.fritzbox.callmonitor] Use phonebook class PytzBox
> 17:21:34 T:139855854028544  NOTICE: [service.fritzbox.callmonitor] 83 entries from fritz.box loaded, 0 images cached
> 17:21:34 T:139855854028544  NOTICE: [service.fritzbox.callmonitor] Connected, listen to fritz.box on port 1012

I'll close this issue.
