### ISSUE TITLE
Issue with iCloud modules with Android

### ISSUE THREAD

**Issue by b-jesch** [b-jesch/service.fritzbox.callmonitor#6]
See here: 
[http://www.kodinerds.net/index.php/Thread/43850-RELEASE-Noch-ein-Addon-f%C3%BCr-die-Fritzbox-Fritzbox-Callmonitor/?postID=306304#post306304](http://www.kodinerds.net/index.php/Thread/43850-RELEASE-Noch-ein-Addon-f%C3%BCr-die-Fritzbox-Fritzbox-Callmonitor/?postID=306304#post306304)

Sorry, haven't time to check yet.

**Comment by lutzleonhardt** [comment]
Hi @b-jesch,

sorry for the long delay.
I've found the solution here:
#http://stackoverflow.com/questions/33175763/how-to-use-logging-nullhandler-in-python-2-6

I hope it will work now correctly.

**Comment by b-jesch** [comment]
Hi Lutz,

seems to be solved: http://www.kodinerds.net/index.php/Thread/43850-RELEASE-Noch-ein-Addon-f%C3%BCr-die-Fritzbox-Fritzbox-Callmonitor/?postID=313833#post313833

I'll wait for the 2nd response and close issue if succesfull.

**Comment by b-jesch** [comment]
http://www.kodinerds.net/index.php/Thread/43850-RELEASE-Noch-ein-Addon-f%C3%BCr-die-Fritzbox-Fritzbox-Callmonitor/?postID=313857#post313857

Closed.
