### ISSUE TITLE
Stop Screensaver on calls

### ISSUE THREAD

**Issue by lutzleonhardt** [b-jesch/service.fritzbox.callmonitor#7]
Any idea how to implemen this? There is only a builtin command for ActivateScreensaver.
That's all I've found about this:

http://forum.kodi.tv/showthread.php?tid=250636

**Comment by b-jesch** [comment]
I'll take some investigations next week. I've already worked with JSON within Kodi addons so this shouldn't be a problem.

**Comment by b-jesch** [comment]
Tried this out. JSON will indeed change the screensaver from actual saver to none and backwards but don't stop/deactivate a screensaver that is currently running.
