### ISSUE TITLE
No configuration possible

### ISSUE THREAD

**Issue by franky384** [b-jesch/service.fritzbox.callmonitor#8]
On Kodi 17 Krypton beta 3 it's not possible to configure the plugin, the configure field is greyed out.
Windows 10 32bit, fritzbox callmonitor plugin 2.0.2, the older version 1.?? worked on jarvis.

**Comment by b-jesch** [comment]
Will take a look about this later. I don't use Krypton nor Windows. Will be a little bit difficult.

**Comment by franky384** [comment]
No matter, i just installed v1.4.2, this one works without problems, in krypton.
